// Copyright 2022 Jeremy Edwards
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Package main is the entry point for certtool.
package main

import (
	"flag"
	"fmt"
	"os"
	"slices"
	"strconv"
	"strings"
	"time"

	"github.com/cloudfra/certtool/internal"
	"github.com/cloudfra/certtool/pkg/certtool"
	"go.uber.org/zap"
)

var (
	publicCertificate = flag.String("public-certificate", "app.cert", "X.509 public certificate file to generate.")
	privateKey        = flag.String("private-key", "app.key", "Private key file to generate.")

	ca = flag.Bool("ca", false, "Generates a root certificate. Use this to establish a chain of trust with derived certificates.")

	commonName         = flag.String("common-name", "", "Common Name (CN) field of the X.509 certificate subject. Defaults to the --organization value.")
	country            = flag.String("country", "US", "Country (C) field of the X.509 certificate subject (e.g. US, CA, GB).")
	organization       = flag.String("organization", "cloudfra", "Organization (O) field of the X.509 certificate subject.")
	organizationalUnit = flag.String("organizational-unit", "gows", "Organizational Unit (OU) field of the X.509 certificate subject.")
	locality           = flag.String("locality", "Seattle", "Locality (L) field of the X.509 certificate subject, typically the city name.")
	province           = flag.String("province", "WA", "Province or state (ST) field of the X.509 certificate subject.")

	validity  = flag.Duration("validity", time.Hour*24*365, "How long the certificate is valid for, as a Go duration (e.g. 8760h, 720h, 24h).")
	hostnames = flag.String("hostnames", "", "Comma-separated list of hostnames and IP addresses to include as Subject Alternative Names (SANs).")
	keyType   = flag.String("key-type", "RSA-2048", "Key algorithm and length. Supported values: RSA-2048, RSA-4096, ECDSA-224, ECDSA-256, ECDSA-384, ECDSA-521. Default for --code-sign is the profile default.")
	ports     = flag.String("ports", "", "Comma-separated list of ports to include as Subject Alternative Names (SANs). Ports are expanded on the hostnames that are specified.")

	parentPublicCertificate = flag.String("parent-public-certificate", "", "(optional) Parent public certificate. If set, the output certificate will trust the parent.")
	parentPrivateKey        = flag.String("parent-private-key", "", "(optional) Parent private key. Required if -parent-public-certificate is set, private key for the parent public certificate.")

	codeSigning = flag.Bool("code-sign", false, "Generates a code signing certificate for binary signing instead of a TLS certificate.")
	target      = flag.String("target", "", "Platform profile for --code-sign. Values: windows7 (win7/windows8/win8), windows10 (win10), windows11 (win11), linux. Default: windows10.")
	pfxOutput   = flag.String("pfx-output", "codesign.pfx", "Output path for the PKCS#12 (.pfx) file. Used with --code-sign for Windows targets.")
	pfxPassword = flag.String("pfx-password", "", "Password for the PKCS#12 (.pfx) file. Empty means no password.")

	chain     = flag.Int("chain", 0, "Generate a certificate chain of N certificates (root CA + intermediates + leaf). Must be >= 2.")
	hierarchy = flag.String("hierarchy", "", "Path to a YAML file defining a certificate hierarchy tree.")
	outputDir = flag.String("output-dir", ".", "Output directory for certificates generated by --chain or --hierarchy.")

	version = flag.Bool("version", false, "Print version and build information, then exit.")
)

const (
	algorithmRSA          = "RSA"
	algorithmECDSA        = "ECDSA"
	defaultCodeSignTarget = "windows10"
)

func main() {
	os.Exit(certtoolMain())
}

// certtoolMain runs the tool and returns the process exit code.
func certtoolMain() int {
	flag.Parse()

	if *version {
		fmt.Printf("certtool %s (built %s)\n", internal.Version(), internal.Buildstamp())
		return 0
	}

	if *target != "" && !*codeSigning {
		zap.S().Warn("--target is set but --code-sign is not; --target will be ignored")
	}

	if err := validateModeFlags(); err != nil {
		zap.S().Error(err)
		return 1
	}

	if *chain > 0 || *hierarchy != "" {
		if err := runHierarchyMode(); err != nil {
			zap.S().Error(err)
			return 1
		}
		return 0
	}

	args, err := argsFromFlags()
	if err != nil {
		zap.S().Error(err)
		return 1
	}

	if err := generateAndWriteKeyPair(args); err != nil {
		zap.S().Error(err)
		return 1
	}

	return 0
}

func validateModeFlags() error {
	hasChain := *chain > 0
	hasHierarchy := *hierarchy != ""
	if hasChain && hasHierarchy {
		return fmt.Errorf("--chain and --hierarchy are mutually exclusive")
	}
	if (hasChain || hasHierarchy) && *parentPublicCertificate != "" {
		return fmt.Errorf("--parent-public-certificate cannot be used with --chain or --hierarchy")
	}
	return nil
}

func runHierarchyMode() error {
	defaults, err := argsFromFlagsForHierarchy()
	if err != nil {
		return err
	}

	var nodes []certtool.HierarchyNode
	if *chain > 0 {
		nodes, err = certtool.ChainToHierarchy(*chain, defaults)
		if err != nil {
			return err
		}
	} else {
		nodes, err = certtool.ParseHierarchyFile(*hierarchy)
		if err != nil {
			return err
		}
	}

	results, err := certtool.GenerateHierarchy(nodes, defaults, *outputDir)
	if err != nil {
		return err
	}

	for _, r := range results {
		zap.S().Infof("Generated %s: %s, %s", r.CN, r.CertPath, r.KeyPath)
	}
	return nil
}

func argsFromFlagsForHierarchy() (*certtool.Args, error) {
	if *validity <= 0 {
		return nil, fmt.Errorf("--validity must be a positive duration, got %s", *validity)
	}

	portList, err := splitInts(*ports)
	if err != nil {
		return nil, err
	}

	var kt *certtool.KeyType
	algorithm, keyLength, err := stringToKeyType(*keyType)
	if err != nil {
		return nil, err
	}
	kt = &certtool.KeyType{Algorithm: algorithm, KeyLength: keyLength}

	return &certtool.Args{
		CommonName:         *commonName,
		Country:            *country,
		Organization:       *organization,
		OrganizationalUnit: *organizationalUnit,
		Locality:           *locality,
		Province:           *province,
		Validity:           *validity,
		Hostnames:          splitStrings(*hostnames),
		Ports:              portList,
		KeyType:            kt,
	}, nil
}

func generateAndWriteKeyPair(args *certtool.Args) error {
	kp, err := certtool.GenerateKeyPair(args)
	if err != nil {
		return err
	}
	if len(kp.PFX) > 0 {
		return certtool.WritePFX(kp, *pfxOutput)
	}
	return certtool.WriteKeyPair(kp, *publicCertificate, *privateKey)
}

func argsFromFlags() (*certtool.Args, error) {
	var parent *certtool.KeyPair

	// Detect if --key-type was explicitly set by the user (not just the default value).
	// flag.Visit only visits flags explicitly set via flag.Parse or flag.Set.
	var keyTypeExplicitlySet bool
	flag.Visit(func(f *flag.Flag) {
		if f.Name == "key-type" {
			keyTypeExplicitlySet = true
		}
	})

	var kt *certtool.KeyType
	if keyTypeExplicitlySet || !*codeSigning {
		algorithm, keyLength, err := stringToKeyType(*keyType)
		if err != nil {
			return nil, err
		}
		kt = &certtool.KeyType{Algorithm: algorithm, KeyLength: keyLength}

		// Warn if the user explicitly chose ECDSA for a Windows 7 target.
		if *codeSigning && strings.ToUpper(algorithm) == algorithmECDSA {
			effectiveTarget := *target
			if effectiveTarget == "" {
				effectiveTarget = defaultCodeSignTarget
			}
			if profile, profErr := certtool.GetProfile(effectiveTarget); profErr == nil && profile.LegacyPFX {
				zap.S().Warn("ECDSA code signing certs are not supported by Windows 7 signtool.exe; proceeding with user-specified key type")
			}
		}
	}
	// If kt is nil and codeSigning is true, fillDefaults resolves the key type from the profile.

	var err error
	if *parentPublicCertificate != "" {
		parent, err = certtool.ReadKeyPairFromFile(*parentPublicCertificate, *parentPrivateKey)
		if err != nil {
			return nil, err
		}
	}

	if *validity <= 0 {
		return nil, fmt.Errorf("--validity must be a positive duration, got %s", *validity)
	}

	portList, err := splitInts(*ports)
	if err != nil {
		return nil, err
	}
	return &certtool.Args{
		CA:                 *ca,
		CommonName:         *commonName,
		Country:            *country,
		Organization:       *organization,
		OrganizationalUnit: *organizationalUnit,
		Locality:           *locality,
		Province:           *province,
		Validity:           *validity,
		Hostnames:          splitStrings(*hostnames),
		Ports:              portList,
		KeyType:            kt,
		ParentKeyPair:      parent,
		CodeSigning:        *codeSigning,
		Target:             *target,
		PFXPassword:        *pfxPassword,
	}, nil
}

func stringToKeyType(keyType string) (string, int, error) {
	if keyType == "" {
		return algorithmRSA, 2048, nil
	}
	switch parseKeyTypeKeyName(keyType) {
	case algorithmRSA:
		return parseKeyTypeName(keyType, 2048, []int{2048, 4096})
	case algorithmECDSA:
		return parseKeyTypeName(keyType, 521, []int{224, 256, 384, 521})
	}
	return "", 0, fmt.Errorf("'%s' is not a valid key type", keyType)
}

func parseKeyTypeKeyName(keyTypeName string) string {
	parts := strings.Split(strings.ToUpper(keyTypeName), "-")
	if len(parts) > 0 {
		return parts[0]
	}
	return algorithmRSA
}

func parseKeyTypeName(keyTypeName string, defaultLength int, validValues []int) (string, int, error) {
	parts := strings.Split(strings.ToUpper(keyTypeName), "-")
	if len(parts) > 2 {
		return "", 0, fmt.Errorf("key type '%s' is not valid", keyTypeName)
	}
	if len(parts) == 0 {
		return "", 0, fmt.Errorf("key type does not have a name")
	}

	algorithm := parts[0]
	keyLength := ""
	if len(parts) == 2 {
		keyLength = parts[1]
	}

	if keyLength == "" {
		return algorithm, defaultLength, nil
	}
	length, err := strconv.Atoi(parts[1])
	if err != nil {
		return "", 0, fmt.Errorf("key type '%s' does not have a valid %s key length", keyTypeName, algorithm)
	}
	if slices.Contains(validValues, length) {
		return algorithm, length, nil
	}

	return "", 0, fmt.Errorf("key type '%s' does not have a valid %s key length", keyTypeName, algorithm)
}

func splitStrings(csv string) []string {
	if csv == "" {
		return nil
	}
	parts := strings.Split(csv, ",")
	for i, p := range parts {
		parts[i] = strings.TrimSpace(p)
	}
	return parts
}

func splitInts(csv string) ([]int, error) {
	if csv == "" {
		return nil, nil
	}
	vals := splitStrings(csv)
	result := make([]int, len(vals))
	for i, v := range vals {
		iv, err := strconv.Atoi(v)
		if err != nil {
			return nil, fmt.Errorf("cannot convert %q to an integer, %w", v, err)
		}
		if iv < 1 || iv > 65535 {
			return nil, fmt.Errorf("port %d is not valid, must be between 1 and 65535", iv)
		}
		result[i] = iv
	}
	return result, nil
}
